[package]
name = "i2c-oled"
version = "0.1.0"
edition = "2021"
authors = ["supdrewin"]
license = "MPL-2.0"

[dependencies]
embedded-graphics = "0.7.1"
embedded-hal = "0.2.7"
i2c-linux = "0.1.2"
ssd1306 = "0.7.0"
